version: '3.8'

services:
  # =============================================================================
  # LOAD BALANCER (NGINX) with SSL termination
  # =============================================================================
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:Z
      - ./ssl:/etc/ssl:Z
    depends_on:
      - app1
      - app2
      - app3
      - frontend
    restart: unless-stopped
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - frontend
      - backend

  # =============================================================================
  # BACKEND APPLICATION INSTANCES (Load Balanced)
  # =============================================================================
  app1: &backend-app
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env.production
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - label=disable
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: ${BACKEND_MEMORY_LIMIT:-1g}
          cpus: '${BACKEND_CPU_LIMIT:-1.0}'
        reservations:
          memory: 512m
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend

  app2:
    <<: *backend-app

  app3:
    <<: *backend-app

  # =============================================================================
  # AI REVIEW SERVICE
  # =============================================================================
  ai-service:
    build: 
      context: ./ai
      dockerfile: Dockerfile
    env_file:
      - .env.production
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3002
      - DATABASE_URL=${DATABASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    expose:
      - "3002"
      - "3003"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - label=disable
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1.0'
        reservations:
          memory: 512m
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend

  # =============================================================================
  # FRONTEND APPLICATION
  # =============================================================================
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env.production
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    expose:
      - "3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - label=disable
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: ${FRONTEND_MEMORY_LIMIT:-512m}
          cpus: '${FRONTEND_CPU_LIMIT:-0.5}'
        reservations:
          memory: 256m
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - frontend

  # =============================================================================
  # DATABASE (PostgreSQL)
  # =============================================================================
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "127.0.0.1:5432:5432"  # Bind to localhost only
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./postgres/init:/docker-entrypoint-initdb.d:Z
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:Z
    secrets:
      - postgres_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - label=disable
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: ${DATABASE_MEMORY_LIMIT:-2g}
          cpus: '${DATABASE_CPU_LIMIT:-1.5}'
        reservations:
          memory: 1g
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend

  # =============================================================================
  # REDIS (Cache & Session Store)
  # =============================================================================
  redis:
    image: redis:7-alpine
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes 
      --maxmemory 1gb 
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 60
      --tcp-backlog 511
    expose:
      - "6379"
    volumes:
      - redis_data:/data:Z
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:Z
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - label=disable
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.5'
        reservations:
          memory: 512m
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend

  # =============================================================================
  # MONITORING - PROMETHEUS
  # =============================================================================
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "127.0.0.1:9090:9090"  # Bind to localhost only
    volumes:
      - ./prometheus/prometheus.prod.yml:/etc/prometheus/prometheus.yml:Z
      - ./prometheus/rules:/etc/prometheus/rules:Z
      - prometheus_data:/prometheus:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION:-30d}'
      - '--web.external-url=https://${FRONTEND_URL}/prometheus/'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - label=disable
      - no-new-privileges:true
    networks:
      - monitoring

  # =============================================================================
  # MONITORING - GRAFANA
  # =============================================================================
  grafana:
    image: grafana/grafana:latest
    ports:
      - "127.0.0.1:3000:3000"  # Bind to localhost only
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_password
      - GF_SECURITY_SECRET_KEY_FILE=/run/secrets/grafana_secret_key
      - GF_SERVER_ROOT_URL=https://${FRONTEND_URL}/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
    volumes:
      - grafana_data:/var/lib/grafana:Z
      - ./grafana/provisioning:/etc/grafana/provisioning:Z
      - ./grafana/dashboards:/var/lib/grafana/dashboards:Z
    secrets:
      - grafana_password
      - grafana_secret_key
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - label=disable
      - no-new-privileges:true
    networks:
      - monitoring

# =============================================================================
# SECRETS MANAGEMENT
# =============================================================================
secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  grafana_password:
    file: ./secrets/grafana_password.txt
  grafana_secret_key:
    file: ./secrets/grafana_secret_key.txt

# =============================================================================
# PERSISTENT VOLUMES
# =============================================================================
volumes:
  redis_data:
    driver: local
    labels:
      backup: "true"
      environment: "production"
  grafana_data:
    driver: local
    labels:
      backup: "true"
      environment: "production"
  postgres_data:
    driver: local
    labels:
      backup: "true"
      environment: "production"
  prometheus_data:
    driver: local
    labels:
      backup: "true"
      environment: "production"

# =============================================================================
# NETWORK ISOLATION
# =============================================================================
networks:
  frontend:
    driver: bridge
    labels:
      description: "Frontend network - DMZ"
  backend:
    driver: bridge
    internal: true
    labels:
      description: "Backend services network - Internal only"
  monitoring:
    driver: bridge
    internal: true
    labels:
      description: "Monitoring network - Internal only"
